### ISSUE TITLE
About the testing time  of 64x64x64 subvolumes

### ISSUE THREAD

**Issue by fl82hope** [camilo-aguilar/3D-Fiber-Segmentation#2]
Great and interesting work! Thanks for your code and data !

I have a question about the testing time with subvolumes of sizes 64x64x64  as input. In the paper, it says all the
models were trained on an NVIDIA-Titan RTX GPU with 25GB of memory with a training time of approximately two
days. The testing time is not provided yet. 

I planned to test the dataset by your provide pretrained model, but the link in the original dataset paper was not available, so I am wondering whether you can test it for me or provide the testing data to me for testing.

Thanks a lot!

**Comment by camilo-aguilar** [comment]
Hi thanks for your interest,

I dont have access to the full data anymore.

If it helps, the testing time for the full volume (subsampled by 2) of the high resolution SFRP dataset (Section 4.3) was of about ~10 hours and it detected around 92k distinct fibers. If you are interested in this dataset I could forward you the contact information
